apiVersion: v1
kind: Service
metadata:
  name: httpdump
  labels:
    app: httpdump
    service: httpdump
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: httpdump